name: github-actions-check
on: [push]
jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: "Flutter get and build release apk"
      - run: flutter pub get
      - run: flutter build apk
      - name: "Upload Apk"
      - uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk

